# Generated by Django 4.2.6 on 2023-10-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PythonApiAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion_type', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
